// lang-es.ts

export const LANG_AM_NAME = 'am';

export const LANG_AM_TRANS = {
  'signout': 'Դուրս գալ',
  'myrequest_tabname' : 'Ամրագրումներ',
  'favorites_tabname' : 'Նախընտրածներ',
  'unacceptedrequests_tabname' : 'Չհաստատված',
  'acceptedrequests_tabname' : 'Հաստատված',
  'donerequests_tabname' : 'Կատարված',
  'name':'Անուն',
  'telephone': 'Հեռախոս',
  'password':'Գաղտնաբառ',
  'service': 'Ծառայություն',
  'signin':'Մուտք',
  'signup': 'Գրանցվել',
  'username': 'Username',
  'address': 'Հասցե',
  'feedbacks': 'Կարծիքներ',
  'images': 'Նկարներ',
  'notices': 'Նշումներ',
  'followers': 'Հետևորդներ',
  'averageRate': 'Գնահատական',
  'startTime': 'Սկիզբ',
  'description': 'Նկարագրություն',
  'status': 'Վիճակը',
  'responseText': 'Պատասխան',
  'duration': 'Տևողություն',
  'endTime': 'Ավարտ',
  'morephotosbtnlabel': 'Նայել նկարներ',
  'reservebtnlabel':'Ամրագրել',
  'followbtnlabel':'Հետևել',
  'callbtnlabel': 'Զանգել հիմա',
  'distance': 'Հեռավորությունը',
  'schedule_tabname': 'Իմ գրաֆիկը',
  'newrequests_tabname': 'Նոր ամրագրումներ',
  'backtopartnerdetails': 'Գնալ իմ էջ',
  'cancelbtnlabel': 'Չեղարկել',
  'savebtnlabel': 'Հիշել',

  //partner translates
  'my_account':'Իմ էջը',
  'notificationmessage':'Դուք ունեք նոր ամրագրումներ, խնդրում ենք այցելել աշխատանքային տիրույթ:',
  'emptynewrequests':"Նոր ամրագրումներ չկան:",
  'services':"Ծառայություններ",
  'price':'Գին',
  'actions':'Գործ-եր',
  'delete':'Ջնջել',
  'edit':'Փոխել',
  'add':'Ավելացնել',
  'change_address':'Փոխել հասցեն',
  'schedule':'Գրաֆիկ',
  'new_requests': 'Նոր ամրագրումներ',
  'workspace':'Աշխատասենյակ',
  'event_details':'Ամրագրման տվյալներ',
  'contact': 'Կոնտակտային տվյալներ',
  'close':'Փակել',
  'complete':'Կատարված է',
  'startDay':'Օրը',
  'isWrongDurationNewRequest':'Խնդրում ենք մուտքագրել տևողություն',
  'message': 'Հաղորդագրություն',
  'accept' : 'Հաստատել',
  'decline' : 'Մերժել',
  'popup_new_request':'Դուք ունեք նոր ամրագրման հայտ, քանակն է՝',
  'ok':'Լավ',
  'welcomepagetext':'Բարի գալուստ ՍՈՍՈ ։) Ձեր մատուցած ծառայությունը գրանցելու համար մուտք գործեք կամ գրանցվեք համակարգում։'
};
